-- 입양 시각 구하기(1)
-- https://programmers.co.kr/learn/courses/30/lessons/59412

SELECT EXTRACT(HOUR FROM DATETIME) HOUR, COUNT(*)
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM DATETIME) BETWEEN 9 AND 20
GROUP BY EXTRACT(HOUR FROM DATETIME)
ORDER BY EXTRACT(HOUR FROM DATETIME);